### ISSUE TITLE
Safety Features - Harmful Content

### ISSUE THREAD

**Issue by Haltroy** [Haltroy/Yorot#34]
Yorot has no safety features nor a way to stop user from entering harmful websites or websites they should not see. For example, a 10 year old kid should never visit a website that contains sexual imagery.

With this new feature, Yorot will display a message to user to ask the parental password. Parents can also create a child profile to keep them safe.

If necessary, government officials or trusted resources can also forbid specific websites (or parts of it) to view (website containing a harmful program, websites that do capture and sell user data for criminal activity, websites that endorse criminal activity, etc.) (previous bracket content can be downgraded to individual pages if the entire website itself is not doing it such as social media sites) from users.

As a neutral developer, I will not allow any bias or political thinking to use this system to silence anyone. This is either going to be used so "little Timmy would not watch furry p**n" or "I visited this site and now there are ads everywhere even on other apps please help". Not "Hey let's ban those memes where they depicted our _[political figure here]_ as _[something funny]_" or "silence the critics because I am still in the same mental age when I was born." things.

**TODO**:
- [ ] Add parental control system.
- [ ] Create an official lists all harmful websites (probably not in this GitHub repository but it will also be official).
- [ ] Get new mods to control that repository.
